// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: protobuf/dapplink-wallet.proto

package dal_wallet_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_ERROR   ReturnCode = 0
	ReturnCode_SUCCESS ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ReturnCode_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_dapplink_wallet_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_protobuf_dapplink_wallet_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

type BusinessRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerToken  string `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId      string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DepositNotify  string `protobuf:"bytes,3,opt,name=deposit_notify,json=depositNotify,proto3" json:"deposit_notify,omitempty"`
	WithdrawNotify string `protobuf:"bytes,4,opt,name=withdraw_notify,json=withdrawNotify,proto3" json:"withdraw_notify,omitempty"`
	TxFlowNotify   string `protobuf:"bytes,5,opt,name=tx_flow_notify,json=txFlowNotify,proto3" json:"tx_flow_notify,omitempty"`
}

func (x *BusinessRegisterRequest) Reset() {
	*x = BusinessRegisterRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterRequest) ProtoMessage() {}

func (x *BusinessRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterRequest.ProtoReflect.Descriptor instead.
func (*BusinessRegisterRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessRegisterRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *BusinessRegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BusinessRegisterRequest) GetDepositNotify() string {
	if x != nil {
		return x.DepositNotify
	}
	return ""
}

func (x *BusinessRegisterRequest) GetWithdrawNotify() string {
	if x != nil {
		return x.WithdrawNotify
	}
	return ""
}

func (x *BusinessRegisterRequest) GetTxFlowNotify() string {
	if x != nil {
		return x.TxFlowNotify
	}
	return ""
}

type BusinessRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BusinessRegisterResponse) Reset() {
	*x = BusinessRegisterResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterResponse) ProtoMessage() {}

func (x *BusinessRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterResponse.ProtoReflect.Descriptor instead.
func (*BusinessRegisterResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessRegisterResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *BusinessRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protobuf_dapplink_wallet_proto protoreflect.FileDescriptor

var file_protobuf_dapplink_wallet_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x6e, 0x6b, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x17, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x27, 0x0a, 0x0f, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x78, 0x5f,
	0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x74, 0x78, 0x46, 0x6c, 0x6f, 0x77, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22,
	0x53, 0x0a, 0x18, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x79, 0x6e, 0x63,
	0x73, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x2a, 0x24, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x32, 0x73, 0x0a, 0x1a, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x57, 0x69, 0x72, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x55, 0x0a, 0x10, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61,
	0x6c, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_dapplink_wallet_proto_rawDescOnce sync.Once
	file_protobuf_dapplink_wallet_proto_rawDescData = file_protobuf_dapplink_wallet_proto_rawDesc
)

func file_protobuf_dapplink_wallet_proto_rawDescGZIP() []byte {
	file_protobuf_dapplink_wallet_proto_rawDescOnce.Do(func() {
		file_protobuf_dapplink_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_dapplink_wallet_proto_rawDescData)
	})
	return file_protobuf_dapplink_wallet_proto_rawDescData
}

var file_protobuf_dapplink_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_dapplink_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_dapplink_wallet_proto_goTypes = []any{
	(ReturnCode)(0),                  // 0: syncs.ReturnCode
	(*BusinessRegisterRequest)(nil),  // 1: syncs.BusinessRegisterRequest
	(*BusinessRegisterResponse)(nil), // 2: syncs.BusinessRegisterResponse
}
var file_protobuf_dapplink_wallet_proto_depIdxs = []int32{
	0, // 0: syncs.BusinessRegisterResponse.code:type_name -> syncs.ReturnCode
	1, // 1: syncs.BusinessMiddleWireServices.businessRegister:input_type -> syncs.BusinessRegisterRequest
	2, // 2: syncs.BusinessMiddleWireServices.businessRegister:output_type -> syncs.BusinessRegisterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_dapplink_wallet_proto_init() }
func file_protobuf_dapplink_wallet_proto_init() {
	if File_protobuf_dapplink_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_dapplink_wallet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_dapplink_wallet_proto_goTypes,
		DependencyIndexes: file_protobuf_dapplink_wallet_proto_depIdxs,
		EnumInfos:         file_protobuf_dapplink_wallet_proto_enumTypes,
		MessageInfos:      file_protobuf_dapplink_wallet_proto_msgTypes,
	}.Build()
	File_protobuf_dapplink_wallet_proto = out.File
	file_protobuf_dapplink_wallet_proto_rawDesc = nil
	file_protobuf_dapplink_wallet_proto_goTypes = nil
	file_protobuf_dapplink_wallet_proto_depIdxs = nil
}
